name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup .NET 8.0
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.x'
        
      - name: Restore Dependencies
        run: dotnet restore ./software/StreamingAead

      - name: Build
        run: dotnet build --no-restore --configuration Release ./software/StreamingAead
        
      - name: Test
        run: dotnet test --verbosity normal --filter "Category != HeavyCompute & Category != LargeStorage" ./software/StreamingAead.Tests.Unit

  publish_to_nuget:
    needs: build_and_test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Setup .NET 8.0
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.x'
      
      - name: Pack
        run: dotnet pack --configuration Release -o ./nupkgs ./software/StreamingAead
        
      - name: Publish to NuGet
        run: dotnet nuget push "./nupkgs/*.nupkg" --source "https://api.nuget.org/v3/index.json" --api-key ${{secrets.NUGET_API_KEY}} --skip-duplicate
